Completed css-brochure-form exercise.
ChorongShin/c0122-code-solutions pull request #15
Opened 2022-01-27 05:07 UTC by ChorongShin

![Screen Shot 2022-01-26 at 9 05 51 PM](https://user-images.githubusercontent.com/91721272/151295508-6ff229a2-65f1-4760-b78a-d47e5ff3ec98.png)

2022-01-27 18:15 UTC, codingcodymiller requested changes
Hey Stella! Your submit button is too close to the select elem ent above it as compared to the example, please revise and submit a new screenshot with your revision.

2022-01-27 19:43 UTC, ChorongShin commented
![Uploading Screen Shot 2022-01-27 at 11.43.34 AM.png…]()

2022-01-27 19:44 UTC, ChorongShin commented
<img width="1260" alt="Screen Shot 2022-01-27 at 11 43 34 AM" src="https://user-images.githubusercontent.com/91721272/151432236-adb8cf4f-8bed-452f-901b-ab3fcd339744.png">

2022-01-28 19:04 UTC, codingcodymiller requested changes
Hey Stella! Now, your submit button is jutting out past the end of the select on the right side, please revise and submit a new screenshot with your revision.

2022-01-28 19:36 UTC, ChorongShin commented
<img width="1428" alt="Screen Shot 2022-01-28 at 11 14 32 AM" src="https://user-images.githubusercontent.com/91721272/151610452-a4345e9b-90ed-47b4-901f-bfd6268fa2aa.png">

2022-01-28 23:02 UTC, codingcodymiller requested changes

2022-01-28 23:02 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-right: 18%;
Oh no!!! That's a **_lot_** of margin. Why is this necessary? There is likely a better way to accomplish this.

2022-01-28 23:02 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-left: 153px;
Oh no!!! That's a **_lot_** of margin. Why is this necessary? There is likely a better way to accomplish this.

2022-01-28 23:50 UTC, ChorongShin commented
<img width="1424" alt="Screen Shot 2022-01-28 at 3 49 18 PM" src="https://user-images.githubusercontent.com/91721272/151636656-530e4dad-1772-4b29-92d2-748c3c9a6c91.png">

2022-01-31 17:23 UTC, codingcodymiller requested changes

2022-01-31 17:23 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  padding-right: 138px;
You can't just change the `margin` to `padding`, that is the same problem.

2022-01-31 17:23 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  padding-left: 153px;
You can't just change the `margin` to `padding`, that is the same problem.

2022-02-01 17:56 UTC, ChorongShin commented
![Screen Shot 2022-02-01 at 9 54 40 AM](https://user-images.githubusercontent.com/91721272/152023908-ff446b50-4e69-4eac-a655-3bc8b929492f.png)

2022-02-01 18:18 UTC, codingcodymiller requested changes

2022-02-01 18:18 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  right: 123px;
Why is this necessary? You already have `text-align: center` on this 🤔

2022-02-01 18:18 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  left: 100px;
You seem to be becoming **_very_** reliant on the `position` property. Let me reiterate that it is meant to be used **_very sparingly_**, and most often for very small adjustments, something like 5-10px. What is the purpose of this?

2022-02-02 02:27 UTC, ChorongShin commented
![Screen Shot 2022-02-01 at 6 25 59 PM](https://user-images.githubusercontent.com/91721272/152083943-5770d917-7727-419d-9dcf-56473622dca9.png)

2022-02-02 18:22 UTC, codingcodymiller approved these changes
Great work!!

2022-02-03 20:47 UTC, merged