Completed css-layout-classes exercise.
ChorongShin/c0122-code-solutions pull request #17
Opened 2022-01-27 21:26 UTC by ChorongShin

<img width="454" alt="Screen Shot 2022-01-27 at 1 23 45 PM" src="https://user-images.githubusercontent.com/91721272/151446349-cae78c4c-8695-49af-9e9b-0ed925be854f.png">

2022-01-27 22:44 UTC, codingcodymiller requested changes

2022-01-27 22:44 UTC, codingcodymiller commented on css-layout-classes/index.html
> +        <div class="row-half">
What is `row-half`? You only need one row class, which should be `row`

2022-01-27 22:44 UTC, codingcodymiller commented on css-layout-classes/index.html
> +        <div class="column-half">
I don't see any CSS for the `column-half` class

2022-01-27 22:44 UTC, codingcodymiller commented on css-layout-classes/index.html
> +        <div class="column-one-third">
I don't see any CSS for the `column-one-third` class

2022-01-28 00:42 UTC, ChorongShin commented
<img width="1280" alt="Screen Shot 2022-01-27 at 4 40 27 PM" src="https://user-images.githubusercontent.com/91721272/151466989-3e242197-b43e-498d-89d1-e473b15a7474.png">

2022-01-28 01:08 UTC, codingcodymiller approved these changes

2022-01-28 01:08 UTC, merged