Completed css-two-column-layout exercise.
ChorongShin/c0122-code-solutions pull request #20
Opened 2022-01-29 19:02 UTC by ChorongShin

![Screen Shot 2022-01-29 at 11 02 30 AM](https://user-images.githubusercontent.com/91721272/151674082-f9814d23-2381-4189-bd65-6d5536a29815.png)

2022-01-31 18:10 UTC, codingcodymiller requested changes

2022-01-31 18:10 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  left: 350px;
This is not the proper way to center a button. Please remember what I taught you in the `css-positioning` exercise, the `position` property is meant to be used for small adjustments, not huge `350px` movements.

2022-02-01 00:57 UTC, ChorongShin commented
![Screen Shot 2022-01-31 at 4 55 46 PM](https://user-images.githubusercontent.com/91721272/151897350-2633ce01-7466-49c9-aa77-6dbdf579e82f.png)

2022-02-01 23:07 UTC, codingcodymiller approved these changes
Nicely done!!

2022-02-01 23:12 UTC, merged