Completed css-canvas-medical exercise.
ChorongShin/c0122-code-solutions pull request #21
Opened 2022-01-30 05:37 UTC by ChorongShin

<img width="1391" alt="Screen Shot 2022-01-29 at 9 30 33 PM" src="https://user-images.githubusercontent.com/91721272/151688088-b6f117da-3131-4a04-b2a6-046defed6e18.png">
<img width="1391" alt="Screen Shot 2022-01-29 at 9 30 41 PM" src="https://user-images.githubusercontent.com/91721272/151688089-86e0eaf7-4f71-4d6f-9015-b43cc334db85.png">
<img width="1375" alt="Screen Shot 2022-01-29 at 9 30 50 PM" src="https://user-images.githubusercontent.com/91721272/151688094-b006ea96-b2e7-471c-bbbb-173fcb1b5c3e.png">

2022-02-02 01:23 UTC, codingcodymiller requested changes
Hey Stella! The text in the "Ready to learn more?" section is the wrong color, and you are missing an overlay on the hero image, the image in the output is a bit more faded than the image itself. I suggest looking back at the `absolute` portion of `css-positioning` for a reminder of how to do an overlay effectively/

2022-02-02 17:47 UTC, ChorongShin commented
![Screen Shot 2022-02-02 at 9 47 05 AM](https://user-images.githubusercontent.com/91721272/152208882-ee11613c-5363-40e9-aa42-e30549d04fbf.png)
![Screen Shot 2022-02-02 at 9 47 12 AM](https://user-images.githubusercontent.com/91721272/152208895-5984127d-4b68-4b80-85f9-5aa6ced1a3f8.png)

2022-02-04 18:38 UTC, codingcodymiller requested changes

2022-02-04 18:38 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  left: 239px;
**_woah_**, why does this need such a huge `left` value?

2022-02-05 21:47 UTC, ChorongShin commented
![_Users_chorongshin_repos_c0122-code-solutions_css-canvas-medical_index html (2)](https://user-images.githubusercontent.com/91721272/152660096-24eca832-304d-4a24-bc3e-042f1fd9c075.png)

2022-02-07 18:33 UTC, codingcodymiller approved these changes
Great work!

2022-02-07 18:49 UTC, merged