Completed html-forms exercise.
ChorongShin/c0122-code-solutions pull request #7
Opened 2022-01-25 22:59 UTC by ChorongShin

![Uploading Screen Shot 2022-01-25 at 2.58.27 PM.png…]()

2022-01-25 23:01 UTC, ChorongShin commented
<img width="893" alt="Screen Shot 2022-01-25 at 2 58 27 PM" src="https://user-images.githubusercontent.com/91721272/151074149-de6c16fc-df36-4ef1-80d2-69ffe79c56ba.png">

2022-01-25 23:04 UTC, codingcodymiller requested changes

2022-01-25 23:04 UTC, codingcodymiller commented on html-forms/index.html
> +      <label for = "email">Email</label>
The equal signs for attributes in HTML should not have any spaces before or after them, please revise.

2022-01-25 23:04 UTC, codingcodymiller commented on html-forms/index.html
> +              </div>
Your indentation started to get a bit wonky here 😬

2022-01-25 23:08 UTC, ChorongShin commented
<img width="1087" alt="Screen Shot 2022-01-25 at 3 08 27 PM" src="https://user-images.githubusercontent.com/91721272/151074992-82dab905-c134-4b5a-bb9a-f5072aad8c83.png">

2022-01-25 23:12 UTC, codingcodymiller requested changes
Still some indentation issues, please revise

2022-01-26 00:30 UTC, ChorongShin commented
![Uploading Screen Shot 2022-01-25 at 4.28.56 PM.png…]()

2022-01-26 00:31 UTC, ChorongShin commented
<img width="807" alt="Screen Shot 2022-01-25 at 4 28 56 PM" src="https://user-images.githubusercontent.com/91721272/151082640-6a2b8288-3f2a-4ae4-ad6c-1d0d1f9ece2b.png">

2022-01-26 00:53 UTC, codingcodymiller requested changes
Hey Stella! This indentation is still pretty significantly off, please double-check that you ran the `npm ci` command in your `c0122-code-solutions` directory, the programs installed with that command should be helping you keep your formatting consistent.

2022-01-26 17:09 UTC, codingcodymiller approved these changes

2022-01-26 17:37 UTC, merged